// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
    {
        "name": "OpenTypePixelFont",
        "status": false,
        "description": "Draw true type fonts using opentype.js",
        "parameters": {
            "fontList": "[\"{\\\"family\\\":\\\"GameFont\\\",\\\"file\\\":\\\"PixelOperator.ttf\\\",\\\"snapToPixel\\\":\\\"true\\\",\\\"baseSize\\\":\\\"16\\\",\\\"unicode-range\\\":\\\"U+0-10FFFF\\\"}\",\"{\\\"family\\\":\\\"rmmz-mainfont\\\",\\\"file\\\":\\\"virtue_bold_edit.ttf\\\",\\\"snapToPixel\\\":\\\"true\\\",\\\"baseSize\\\":\\\"16\\\",\\\"unicode-range\\\":\\\"U+0-10FFFF\\\"}\",\"{\\\"family\\\":\\\"rmmz-numberfont\\\",\\\"file\\\":\\\"virtue_bold_edit.ttf\\\",\\\"snapToPixel\\\":\\\"true\\\",\\\"baseSize\\\":\\\"{20:16,34:24,30:24}\\\",\\\"unicode-range\\\":\\\"U+0-10FFFF\\\"}\"]"
        }
    },
    {
        "name": "hardcoded",
        "status": true,
        "description": "я люблю котиков, вы знали?",
        "parameters": {}
    },
    {
        "name": "WD_Core",
        "status": false,
        "description": "This is a parent plugin that handles the common basic functions of other plugins",
        "parameters": {
            "autoWrapMin": "8",
            "autoSizeMin": "5",
            "addPixiFlag": "false"
        }
    },
    {
        "name": "WD_Translation",
        "status": false,
        "description": "Allow you to translate the game",
        "parameters": {
            "defaultLanguage": "{\"language\":\"English\"}",
            "defaultCombatMiss": "ПРОМАХ",
            "defaultOptionOn": "ВКЛ",
            "defaultOptionOff": "ОТКЛ",
            "defaultOptionLanguage": "Select Language:",
            "mainTranslation": "[]",
            "optionsLanguageFlag": "false"
        }
    },
    {
        "name": "MUSH_Audio_Engine",
        "status": true,
        "description": "[v.1.08] Implement the Mush Audio Engine features.",
        "parameters": {
            "DevelopperMode": "false",
            "GeneralFeatures": "",
            "FEA_UIS": "true",
            "FEA_VSC": "false",
            "FEA_SPAPAN": "true",
            "FEA_MAPAUTOPLAY": "false",
            "VolumeBalance": "",
            "VB_BGM": "100",
            "VB_BGS": "100",
            "VB_ME": "100",
            "VB_SE": "100",
            "VB_UIS": "100",
            "VB_VSC": "100",
            "SeUisVarFeatures": "",
            "StaticFollowSe": "true",
            "SeVarFeatures": "",
            "SePitchVarFeature": "true",
            "SePitchVarRange": "5",
            "SeVolumeVarFeature": "true",
            "SeVolumeVarRange": "3",
            "UisVarFeatures": "",
            "UisPitchVarFeature": "true",
            "UisPitchVarRange": "5",
            "UisVolumeVarFeature": "true",
            "UisVolumeVarRange": "3",
            "MenuOptions": "",
            "MasterOptions": "",
            "OptMasterFeature": "true",
            "OptMasterText": "Общая громкость",
            "UisOptions": "",
            "OptUisFeature": "true",
            "OptUisText": "Громкость звуков интерфейса",
            "VscOptions": "",
            "OptVscFeature": "false",
            "OptVscText": "VSC Volume"
        }
    },
    {
        "name": "PluginCommonBase",
        "status": true,
        "description": "Plugin Analysis Common Base",
        "parameters": {}
    },
    {
        "name": "TemplateEvent",
        "status": true,
        "description": "Template Events",
        "parameters": {
            "TemplateMapId": "1",
            "KeepEventId": "true",
            "OverrideTarget": "",
            "AutoOverride": "false",
            "IntegrateNote": "0"
        }
    },
    {
        "name": "ItemReqForSkill",
        "status": true,
        "description": "Item Requirement for Skill",
        "parameters": {}
    },
    {
        "name": "bunchastuff",
        "status": true,
        "description": "",
        "parameters": {}
    },
    {
        "name": "WD_ItemUse",
        "status": true,
        "description": "Creates a window that let the player select an item and returns the ID",
        "parameters": {
            "itemSelector": "{\"selectorMode\":\"mode1\",\"includeEquip\":\"false\",\"metaTag\":\"69\"}",
            "showDesc": "true",
            "returnMode": "{\"returnMode\":\"mode1\",\"idVar\":\"70\",\"catVar\":\"71\",\"resultSwitch\":\"15\"}"
        }
    },
    {
        "name": "TLB_LimitedShopStock",
        "status": true,
        "description": "This plugin adds limited inventory to shops.",
        "parameters": {
            "general": "",
            "stockText": "(осталось %1)",
            "soldOutText": "(ПРОДАНО)",
            "defaultRestockTime": "-1",
            "defaultRestockQuantity": "1",
            "defaultStockMax": "99"
        }
    },
    {
        "name": "FilterControllerMZ",
        "status": true,
        "description": "FilterControllerMZ",
        "parameters": {
            "decimalVariable": "true",
            "displacementImage": "DisplacementMap",
            "global-enable Settings": "",
            "enabledAll-ShowInOptionMenu": "false",
            "enabledAll-Text": "Filter Effects Enabled",
            "enabledAll-DefaultValue": "true"
        }
    },
    {
        "name": "WD_ConditionalChoice",
        "status": true,
        "description": "Allow to input a check in the \"Show Choice\" that disables or hide the choice.",
        "parameters": {
            "disabledSE": "",
            "hiddenDefault": "hidden1",
            "alternativeText": "[]",
            "errorHandling": "error1"
        }
    },
    {
        "name": "OrangeGreenworks",
        "status": true,
        "description": "Steamworks Integration <OrangeGreenworks>",
        "parameters": {}
    },
    {
        "name": "Cyclone-Steam",
        "status": true,
        "description": "Integrate your game with the Steamworks SDK - 1.00.01\n<pluginName:CycloneSteam>",
        "parameters": {}
    },
    {
        "name": "GALV_LayerGraphicsMZ",
        "status": true,
        "description": "(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.",
        "parameters": {
            "fixPosition": "true"
        }
    },
    {
        "name": "TextPicture",
        "status": true,
        "description": "Displays text as a picture.",
        "parameters": {}
    },
    {
        "name": "HPConsumeSkill",
        "status": true,
        "description": "make the skill that consumes HP, not only MP and/or TP",
        "parameters": {
            "Consume HP Color": "17"
        }
    },
    {
        "name": "Windowskinchange",
        "status": true,
        "description": "Reassign the windowskin mid-game.",
        "parameters": {}
    },
    {
        "name": "wordcountCalc",
        "status": false,
        "description": "",
        "parameters": {}
    },
    {
        "name": "GRB_NoCharSmoothingOnZoom",
        "status": true,
        "description": "Remove character smoothing when zooming.",
        "parameters": {}
    },
    {
        "name": "TDDP_PixelPerfect",
        "status": true,
        "description": "1.1.1 Enable pixel perfect scaling mode for your game",
        "parameters": {
            "enableIngameOptions": "false",
            "labels": "",
            "en": "Pixel Perfect Mode",
            "ja": "ピクセルパーフェクトモード",
            "zh": "像素完美模式",
            "ko": "픽셀 퍼펙트 모드",
            "ru": "Режим Pixel Perfect"
        }
    },
    {
        "name": "Hime_PreTitleEvents",
        "status": true,
        "description": "Build your own sequence of events that should occur before\r\nthe title screen begins",
        "parameters": {
            "Pre-Title Map ID": "307",
            "Use As Title": "false"
        }
    },
    {
        "name": "FullscreenToggle",
        "status": false,
        "description": "Adds an option in the menu to toggle between fullscreen and windowed mode with a fade to black effect.",
        "parameters": {}
    },
    {
        "name": "Mano_InputConfig",
        "status": true,
        "description": "ゲームの操作に関する機能をまとめて管理します。\r\nユーザーによる拡張も支援します。",
        "parameters": {
            "color": "{\"normal\":\"#22e488\",\"mandatory\":\"#22e488\",\"move\":\"#22e488\",\"extends\":\"#22e488\"}",
            "basicOk": "{\"name\":\"{\\\"jp\\\":\\\"決定\\\",\\\"en\\\":\\\"OK\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "basicCancel": "{\"name\":\"{\\\"jp\\\":\\\"キャンセル\\\",\\\"en\\\":\\\"cancel\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "basicShift": "{\"name\":\"{\\\"jp\\\":\\\"ダッシュ\\\",\\\"en\\\":\\\"dash\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "basicMenu": "{\"name\":\"{\\\"jp\\\":\\\"メニュー\\\",\\\"en\\\":\\\"menu\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "basicEscape": "{\"name\":\"{\\\"jp\\\":\\\"メニュー/キャンセル\\\",\\\"en\\\":\\\"menu/cancel\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "basicPageup": "{\"name\":\"{\\\"jp\\\":\\\"次\\\",\\\"en\\\":\\\"next\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "basicPagedown": "{\"name\":\"{\\\"jp\\\":\\\"前\\\",\\\"en\\\":\\\"prev\\\"}\",\"keyText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\",\"helpText\":\"{\\\"jp\\\":\\\"\\\",\\\"en\\\":\\\"\\\"}\"}",
            "mapperDelete": "{\"jp\":\"設定を消去\",\"en\":\"CLEAR\"}",
            "extendsMapper": "[\"{\\\"keys\\\":\\\"\\\",\\\"keySetting\\\":\\\"{\\\\\\\"keys\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"text\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"jp\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"en\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"}\\\\\\\"}\\\",\\\"button\\\":\\\"NaN\\\",\\\"name\\\":\\\"{\\\\\\\"jp\\\\\\\":\\\\\\\"Backspace\\\\\\\",\\\\\\\"en\\\\\\\":\\\\\\\"Backspace\\\\\\\"}\\\",\\\"helpText\\\":\\\"{\\\\\\\"jp\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"en\\\\\\\":\\\\\\\"\\\\\\\"}\\\",\\\"event\\\":\\\"{\\\\\\\"id\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"inputType\\\\\\\":\\\\\\\"0\\\\\\\"}\\\",\\\"touchButton\\\":\\\"\\\",\\\"adovanced\\\":\\\"{\\\\\\\"symbol\\\\\\\":\\\\\\\"backspace\\\\\\\",\\\\\\\"overwrite\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"mandatory\\\\\\\":\\\\\\\"false\\\\\\\"}\\\",\\\"enabled\\\":\\\"true\\\"}\"]",
            "eventList": "[]",
            "GamepadIsNotConnectedText": "{\"jp\":\"\\\"ゲームパッドが接続されていません\\\\nボタンを押して再度試してください\\\"\",\"en\":\"\\\"The gamepad is not connected.\\\\nPress the button and try again.\\\"\"}",
            "needButtonDetouchText": "{\"jp\":\"\\\"コンフィグを終了するために、\\\\nボタンから手を放してください。\\\"\",\"en\":\"\\\"Release the button to exit the config.\\\"\"}",
            "apply": "{\"width\":\"4\",\"text\":\"{\\\"jp\\\":\\\"設定を保存\\\",\\\"en\\\":\\\"SAVE & EXIT\\\"}\"}",
            "rollback": "{\"width\":\"4\",\"text\":\"{\\\"jp\\\":\\\"変更前に戻す\\\",\\\"en\\\":\\\"rollback\\\"}\"}",
            "reset": "{\"width\":\"4\",\"text\":\"{\\\"jp\\\":\\\"初期設定に戻す\\\",\\\"en\\\":\\\"RESET TO DEFAULT\\\"}\"}",
            "WASD": "{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"WASD\\\",\\\"en\\\":\\\"WASD\\\"}\"}",
            "style": "{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"設定方法変更\\\",\\\"en\\\":\\\"Change setting style\\\"}\"}",
            "changeLayout": "{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"JIS/US\\\",\\\"en\\\":\\\"JIS/US\\\"}\"}",
            "exit": "{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"やめる\\\",\\\"en\\\":\\\"CANCEL\\\"}\"}",
            "gamepadConfigCommandText": "{\"jp\":\"ゲームパッドコンフィグ\",\"en\":\"Управление с геймпада\"}",
            "keyConfigCommandText": "{\"jp\":\"キーコンフィグ\",\"en\":\"Управление с клавиатуры\"}",
            "gamepadBackground": "",
            "keyBackground": "",
            "SettingsForYEP_OptionsCore": "{\"gamepad\":\"true\",\"Keyboard\":\"true\"}"
        }
    },
    {
        "name": "regenDamageResistFix",
        "status": true,
        "description": "",
        "parameters": {}
    },
    {
        "name": "deleteNameInput",
        "status": true,
        "description": "",
        "parameters": {}
    },
    {
        "name": "DeepBasement",
        "status": true,
        "description": "",
        "parameters": {}
    },
    {
        "name": "Hendrix_Localization",
        "status": false,
        "description": "A localization system that replaces game text based on CSV data. The best localization plugin <3",
        "parameters": {
            "Exact Text": "true",
            "decor1": "===============================",
            "Adding Maps name": "true",
            "Extract Names (MZ)": "true",
            "Extract Database Entries": "true",
            "Extract Variable Text": "true",
            "Extract Show Picture": "false",
            "Extract Play Movies": "false",
            "Extract Script Call": "true",
            "Extract Plugin Command Text": "true",
            "Extract Comments": "false",
            "Exclude Name Text": "false",
            "decor2": "===============================",
            "Partial Matching": "false",
            "Use Translation Cache": "false",
            "Auto Refresh Pictures": "false",
            "decor3": "===============================",
            "Languages": "[\"{\\\"Name\\\":\\\"English\\\",\\\"Symbol\\\":\\\"en\\\",\\\"Font\\\":\\\"\\\",\\\"FontSize\\\":\\\"22\\\"}\",\"{\\\"Name\\\":\\\"French\\\",\\\"Symbol\\\":\\\"fr\\\",\\\"Font\\\":\\\"\\\",\\\"FontSize\\\":\\\"22\\\"}\",\"{\\\"Name\\\":\\\"Spanish\\\",\\\"Symbol\\\":\\\"sp\\\",\\\"Font\\\":\\\"\\\",\\\"FontSize\\\":\\\"22\\\"}\",\"{\\\"Name\\\":\\\"Chinese\\\",\\\"Symbol\\\":\\\"cn\\\",\\\"Font\\\":\\\"\\\",\\\"FontSize\\\":\\\"22\\\"}\"]",
            "Default Language": "en",
            "Add Language Command to Title": "false",
            "decor4": "===============================",
            "Excluded Symbols": "[\"{\\\"Symbol\\\":\\\"\\\\\\\\n<*>\\\"}\"]"
        }
    },
    {
        "name": "TunicateScripts",
        "status": true,
        "description": "",
        "parameters": {}
    },
    {
        "name": "SuperFrontViewMZ",
        "status": false,
        "description": "Enhances the production of front view battle.",
        "parameters": {
            "controlAnimation": "true",
            "window": "{\"variablePosition\":\"false\",\"autoStatusWidth\":\"true\",\"maxWidth\":\"192\",\"frameVisible\":\"false\",\"backSpriteVisible\":\"true\",\"noBackGround\":\"false\",\"noBackGroundRect\":\"false\",\"mixSkillTypes\":\"false\"}",
            "actor": "{\"nonFrameFaceHeight\":\"false\",\"stateSprite\":\"false\",\"stateSpriteX\":\"0\",\"stateSpriteY\":\"0\",\"stepForward\":\"false\",\"extraMotion\":\"false\",\"whiten\":\"true\",\"selectionEffect\":\"false\",\"damageEffect\":\"shake\",\"amplitude\":\"4\",\"randomShake\":\"false\",\"damageOffsetY\":\"-32\",\"collapseEffect\":\"flashy\",\"enableMirror\":\"false\"}",
            "enemy": "{\"stepForward\":\"false\",\"extraMotion\":\"false\",\"whiten\":\"true\",\"damageEffect\":\"blink\",\"amplitude\":\"4\",\"randomShake\":\"false\",\"collapseEffect\":\"flashy\"}"
        }
    }
];
